---
- name: Install dependencies
  apt:
    pkg: ["git", "curl", "build-essential", "libssl-dev"]
    update_cache: yes
    cache_valid_time: 3600
  become: true
  tags: nvm

- name: Install nvm {{ nvm_version }}
  git:
    repo: https://github.com/creationix/nvm.git
    dest: "{{ nvm_install_path }}"
    version: "{% if nvm_version!='HEAD' %}v{% endif %}{{ nvm_version }}"
  tags: nvm

- name: Source nvm in ~/.profile
  lineinfile:
    dest: ~/.profile
    line: . {{ nvm_install_path }}/nvm.sh
    create: yes
  tags: nvm

- name: Install Node.js {{ nvm_node_version }}
  shell: . ~/.profile && nvm install {{ nvm_node_version }}
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stderr"
  tags: nvm

- name: Check if {{ nvm_node_version }} is the default Node.js version
  shell: . ~/.profile && nvm ls --no-colors | grep -e 'default -> {{ nvm_node_version }}'
  register: nvm_check_default
  changed_when: False
  failed_when: False
  tags: nvm

- name: Set default Node.js version to {{ nvm_node_version }}
  shell: . ~/.profile && nvm alias default {{ nvm_node_version }}
  when: nvm_check_default.rc != 0
  tags: nvm
